
package main;
import chemcam.*;
import java.io.*;
import org.json.simple.JSONObject;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
public class ControllerPanel extends javax.swing.JPanel{
    public RoverThread controllerListenThread;
    private RoverThread controllerConnectThread;
    public ControllerPanel(){
        ControllerRunnable controller = null;
        initComponents();        
        try{
            controller = new ControllerRunnable(10011){
                @Override
                public void run(){
                    try{
<<<<<<< HEAD
                        jTextArea1.append("Controller - Server: Waiting for report.\n");   
                        getRunnableServerSocket().openSocket();
                        Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS").setPrettyPrinting().create();
                        try(ObjectInputStream ois = new ObjectInputStream(getRunnableServerSocket().getSocket().getInputStream())){
                            while(true){
                                String jsonString = (String)ois.readObject();
                                ArrayList<ReportObject> report = gson.fromJson(jsonString, new TypeToken<ArrayList<ReportObject>>(){}.getType());                                
                                if(!report.isEmpty()){
                                    jTextArea1.append("Controller - Server: Report recieved from Agent.\n");
                                    jTextArea1.append(gson.toJson(report) + "\n");
                                    jTextArea1.append("Controller - Server: Storing report to database.\n");
                                }
                                Thread.sleep(3000);
=======
                        while(true){
                            jTextArea1.append("Controller - Server Thread: Waiting for report.\n");
                            getRunnableServerSocket().openSocket();
                            ObjectInputStream ois = new ObjectInputStream(getRunnableServerSocket().getSocket().getInputStream());
                            ObjectOutputStream oos = new ObjectOutputStream(getRunnableServerSocket().getSocket().getOutputStream());                          
                            JSONObject report = (JSONObject)ois.readObject();
                            if(!report.isEmpty()){
                                jTextArea1.append("Controller - Server Thread: Report recieved from Agent.\n");
                                jTextArea1.append("Controller - Server Thread: Storing report to database.\n");
                                // TO_DO
>>>>>>> 67e7d3c445751282846667e5a54183d65c82864a
                            }
                            ois.close();
                            oos.close();                            
                        }
                    } 
                    catch(IOException | ClassNotFoundException | InterruptedException exception) {
                        Utils.log("Exception: " + exception + "\n");
                    } 
                }
            };
        }
        catch(IOException socketException){
            Utils.log("IOException on creating new socket: " + socketException + "\n");
        }
        controllerListenThread = new RoverThread(controller, "Controller Server Thread");
        jTextArea2.setText("Command Sequence:\n");
    }
    public RoverThread getControllerListenThread(){
        return controllerListenThread;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jSplitPane1.setDividerSize(2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select A Command", "CCAM_POWER_ON", "CCAM_COOLER_ON", "CCAM_LASER_ON", "CCAM_CWL_WARM", "CCAM_SET_FOCUS", "CCAM_LIBS_WARM", "CCAM_FIRE_LASER", "CCAM_LASER_OFF", "CCAM_COOLER_OFF", "CCAM_POWER_OFF" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Terminate Agent");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("High Priority");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jCheckBox1))
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 153, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea2.setText("Command Sequence:\n");
    }//GEN-LAST:event_jButton1ActionPerformed
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String command = jComboBox1.getSelectedItem().toString();
        if(!command.equals("Select A Command") && !jTextArea2.getText().contains(command)){
            switch(command){
                case "CCAM_POWER_OFF":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_COOLER_ON") && !jTextArea2.getText().contains("CCAM_COOLER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Cooler needs to be turned OFF before turning OFF Power!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_LASER_ON") && !jTextArea2.getText().contains("CCAM_LASER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Laser needs to be turned OFF before turning OFF Power", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;
                case "CCAM_COOLER_ON":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;
                case "CCAM_COOLER_OFF":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(!jTextArea2.getText().contains("CCAM_COOLER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Cooler is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;
                case "CCAM_LASER_ON":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;
                case "CCAM_LASER_OFF":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(!jTextArea2.getText().contains("CCAM_LASER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Laser is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;
                case "CCAM_CWL_WARM":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;
                case "CCAM_LIBS_WARM":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;
                case "CCAM_SET_FOCUS":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(!jTextArea2.getText().contains("CCAM_CWL_WARM")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Continuous-Wave Laser is not Warmed Up!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;
                case "CCAM_FIRE_LASER":
                    if(!jTextArea2.getText().contains("CCAM_POWER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Power is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(!jTextArea2.getText().contains("CCAM_COOLER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Cooler is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_COOLER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Cooler is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(!jTextArea2.getText().contains("CCAM_LASER_ON")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Laser is not ON!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(jTextArea2.getText().contains("CCAM_LASER_OFF")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Laser is already OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(!jTextArea2.getText().contains("CCAM_SET_FOCUS")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Focus is not Set!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else if(!jTextArea2.getText().contains("CCAM_LIBS_WARM")){
                        JOptionPane.showMessageDialog(null, "Chemical Camera's Laser-Induced Breakdown Spectroscopy is not Warmed Up!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else{
                        jTextArea2.append(command + "\n");
                    }
                    break;                    
                default:
                    jTextArea2.append(command + "\n");
                    break;
            }
        }
        else{
            // To do
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] commandList = jTextArea2.getText().split("\n");
        final JSONObject commandsJSON = new JSONObject();
        ControllerRunnable controller = null;
        boolean send = true;
        for(int i = 0; i < commandList.length; i++){
            if(send){
                switch(commandList[i]){
                    case "Command Sequence:":
                        break;
                    case "CCAM_POWER_ON":
                        if(!jTextArea2.getText().contains("CCAM_POWER_OFF")){
                            JOptionPane.showMessageDialog(null, "Chemical Camera's Power is not going to be turned OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                            send = false;
                            break;
                        }
                        else{
                            commandsJSON.put(i, commandList[i]);
                            break;
                        }
                    case "CCAM_COOLER_ON":
                        if(!jTextArea2.getText().contains("CCAM_COOLER_OFF")){
                            JOptionPane.showMessageDialog(null, "Chemical Camera's Cooler is not going to be turned OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                            send = false;
                            break;
                        }
                        else{
                            commandsJSON.put(i, commandList[i]);
                            break;
                        }
                    case "CCAM_LASER_ON":
                        if(!jTextArea2.getText().contains("CCAM_LASER_OFF")){
                            JOptionPane.showMessageDialog(null, "Chemical Camera's Laser is not going to be turned OFF!", "Add Command Error", JOptionPane.ERROR_MESSAGE);
                            send = false;
                            break;
                        }
                        else{
                            commandsJSON.put(i, commandList[i]);
                            break;
                        }
                    default:
                        commandsJSON.put(i, commandList[i]);
                        break;
                }
            }
            else{
                break;
            }
        }
        if(send && !commandsJSON.isEmpty()){
            try{
                controller = new ControllerRunnable(9011, null){
                    @Override
                    public void run(){
                        try{
<<<<<<< HEAD
                            try(ObjectOutputStream oos = new ObjectOutputStream(getRunnableSocket().getSocket().getOutputStream())){
                                RoverThread.sleep(2000);                                
                                oos.writeObject(jsonString);
                                jTextArea1.append("Controller - Client: Commands sent to Agent\n");
                                RoverThread.sleep(1000);
                                oos.flush();
                                oos.close();
                            } 
=======
                            ObjectOutputStream oos = new ObjectOutputStream(getRunnableSocket().getSocket().getOutputStream());
                            ObjectInputStream ois = new ObjectInputStream(getRunnableSocket().getSocket().getInputStream());
                            RoverThread.sleep(2000);
                            jTextArea1.append("Controller - Client Thread: Sending command to Agent\n");
                            oos.writeObject(commandsJSON);
                            RoverThread.sleep(1000);
                            ois.close();
                            oos.close(); 
>>>>>>> 67e7d3c445751282846667e5a54183d65c82864a
                            closeAllRunnable();
                        }
                        catch(InterruptedException | IOException exception){
                            Utils.log("Exception: " + exception + "\n");
                        }
                    }
                };
            }
<<<<<<< HEAD
            catch(IOException exception){
                Utils.log("Exception: " + exception + "\n");
=======
            catch(IOException socketException){
                Utils.log("IOException on creating new socket: " + socketException + "\n");
>>>>>>> 67e7d3c445751282846667e5a54183d65c82864a
            }
            controllerConnectThread = new RoverThread(controller, "Controller Client Thread");
            controllerConnectThread.start();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final JSONObject commandsJSON = new JSONObject();
        ControllerRunnable controller = null;
        commandsJSON.put("Terminate", "Shutdown");
        try{
            controller = new ControllerRunnable(9011, null){
                @Override
                public void run(){
                    try{
                        ObjectOutputStream oos = new ObjectOutputStream(getRunnableSocket().getSocket().getOutputStream());
                        ObjectInputStream ois = new ObjectInputStream(getRunnableSocket().getSocket().getInputStream());
                        jTextArea1.append("Controller: Sending command to Agent\n");
                        oos.writeObject(commandsJSON);
                        ois.close();
                        oos.close(); 
                        closeAllRunnable();
                    }
                    catch(IOException exception){
                        Utils.log("Exception: " + exception + "\n");
                    }
                }
            };
        }
        catch(IOException socketException){
            Utils.log("IOException on creating new socket: " + socketException + "\n");
        }
<<<<<<< HEAD
        if(br != null){
            String line;
            String Commands = "";
            boolean loadsuccessful = true;
            try{
                while((line = br.readLine()) != null){
                    if(jTextArea2.getText().contains(line)){
                        JOptionPane.showMessageDialog(null, "Load Failed! Command Already Exists on the Command Editor.", "Load Command Error", JOptionPane.ERROR_MESSAGE);
                        loadsuccessful = false;
                        break;
                    }
                    // ugly... but hey it does the job... plus we're out of time...
                    else if(!line.equals("CCAM_POWER_ON") && 
                            !line.equals("CCAM_COOLER_ON") && 
                            !line.equals("CCAM_LASER_ON") && 
                            !line.equals("CCAM_CWL_WARM") && 
                            !line.equals("CCAM_SET_FOCUS") && 
                            !line.equals("CCAM_LIBS_WARM") && 
                            !line.equals("CCAM_FIRE_LASER") && 
                            !line.equals("CCAM_LASER_OFF") && 
                            !line.equals("CCAM_COOLER_OFF") && 
                            !line.equals("CCAM_POWER_OFF")){
                        JOptionPane.showMessageDialog(null, "Load Failed! Bogus command detected... Please check \\ChemCamSimulator\\src\\chemcam\\data\\commands.txt.", "Load Command Error", JOptionPane.ERROR_MESSAGE);
                        loadsuccessful = false;
                        break;
                    }
                    Commands += line + "\n";
                }
                br.close();
                if(loadsuccessful){
                    jTextArea2.append(Commands + "\n");
                }
            }
            catch(IOException exception){
                Utils.log("Exception: " + exception + "\n");
            }
=======
        controllerConnectThread = new RoverThread(controller, "Controller Client Thread");
        controllerConnectThread.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final JSONObject commandsJSON = new JSONObject();
        String[] commandList = jTextArea2.getText().split("\n");
        ControllerRunnable controller = null;
        FileWriter fw;
        //commandsJSON.put("Save", "Saving to file..");
        try{
            controller = new ControllerRunnable(9011, null){
                @Override
                public void run(){
                    try{
                        ObjectOutputStream oos = new ObjectOutputStream(getRunnableSocket().getSocket().getOutputStream());
                        ObjectInputStream ois = new ObjectInputStream(getRunnableSocket().getSocket().getInputStream());
                        jTextArea1.append("Controller: Saving commands to File\n");
                        JFileChooser fileChooser = new JFileChooser();
                        fileChooser.setCurrentDirectory(new File("src/data"));
                        if (fileChooser.showSaveDialog(jTextArea2) == JFileChooser.APPROVE_OPTION) {
                          File file = fileChooser.getSelectedFile();
                          FileWriter fw = new FileWriter(fileChooser.getSelectedFile());
                          for(int i = 0; i < commandList.length; i++){
                        	  fw.write(commandList[i] + "\n");
                        	  fw.flush();
                          }
                          
                      	 
                          // save to file
                        }
                        
                			System.out.println("Successfully Copied JSON Object to File...");
                			System.out.println("\nJSON Object: " + commandsJSON);
                		
                        oos.writeObject(commandsJSON);
                        ois.close();
                        oos.close(); 
                        closeAllRunnable();
                    }
                    catch(IOException exception){
                        Utils.log("Exception: " + exception + "\n");
                    }
                }
           /*     public void cleanUp() {
           	     writer.close();
           	}*/
            };
>>>>>>> 67e7d3c445751282846667e5a54183d65c82864a
        }
        catch(IOException socketException){
            Utils.log("IOException on creating new socket: " + socketException + "\n");
        }
        controllerConnectThread = new RoverThread(controller, "Controller Client Thread");
        controllerConnectThread.start();
    }//GEN-LAST:event_jButton3ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
