/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author truol014
 */
public class ChemCamAgentPanel extends javax.swing.JPanel implements Runnable{
    private final int port = 9011;
    public ServerSocket AgentServerSocket;
    public Socket AgentSocket;
    public ChemCamAgentPanel() throws IOException{       
        initComponents();
    }
    @Override
    public void run() {
        try{
            // Establish new Agent Server with port 'port'
            AgentServerSocket = new ServerSocket(port); 
            while(true){
                // Agent server start accepting requests
                AgentSocket = AgentServerSocket.accept();
                jTextArea1.append("Agent: Waiting for command\n");                
                String message;
                // Read from socket to ObjectInputStream object
                try(ObjectInputStream ois = new ObjectInputStream(AgentSocket.getInputStream())) {
                    //convert ObjectInputStream object to String
                    message = (String)ois.readObject();
                    jTextArea1.append("Agent: Command Received from Controller - " + message.toUpperCase() + "\n");
                    try(ObjectOutputStream oos = new ObjectOutputStream(AgentSocket.getOutputStream())){
                        // Write object to Socket
                        oos.writeObject("Controller says Hi Agent - " + message);
                        oos.close();
                    }
                    catch (IOException outputException) {
                        jTextArea1.append("IOException on ObjectOutputStream writeObject: " + outputException + "\n");
                    }
                    ois.close(); 
                    // Terminate the server if client sends exit request
                    if(message.equalsIgnoreCase("exit")){
                        break;
                    }   
                }
                catch (ClassNotFoundException inputException) {
                    jTextArea1.append("ClassNotFoundException on ObjectInputStream readObject: " + inputException + "\n");
                }                 
            }
            jTextArea1.append("Agent: Shutting down Socket Agent!!\n");
            // Close socket 
            AgentSocket.close();                       
        } 
        catch (IOException socketException) {
            jTextArea1.append("IOException on ServerSocket listen: " + socketException + "\n");
        } 
        	
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 153, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
