/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author truol014
 */
public class ChemCamAgentPanel extends javax.swing.JPanel implements Runnable{
    private final int port = 9011;
    public ServerSocket ControllerServerSocket;
    public Socket ControllerSocket;
    public ChemCamAgentPanel() throws IOException{       
        initComponents();
    }
    /**
     * Creates new form ChemCamControllerPanel    /**
     * Creates new form ChemCamControllerPanel
     */
    
    /**
     * Creates new form ChemCamAgentPanel
     */
    @Override
    public void run() {
        try{
            ControllerServerSocket = new ServerSocket(port); 
            while(true){                                
                ControllerSocket = ControllerServerSocket.accept();
                jTextArea1.append("Agent: Waiting for command\n");                
                String message;
                ObjectOutputStream oos;
                //convert ObjectInputStream object to String
                //read from socket to ObjectInputStream object
                try(ObjectInputStream ois = new ObjectInputStream(ControllerSocket.getInputStream())) {
                    //convert ObjectInputStream object to String
                    message = (String)ois.readObject();
                    jTextArea1.append("Agent: Command Received from Controller - " + message.toUpperCase() + "\n");
                    //create ObjectOutputStream object
                    oos = new ObjectOutputStream(ControllerSocket.getOutputStream());
                    //write object to Socket
                    oos.writeObject("Controller says Hi Agent - " + message);
                    //close resources
                    ois.close();
                }
                oos.close();
                //getRoverServerSocket().closeSocket();
                //terminate the server if client sends exit request
                if(message.equalsIgnoreCase("exit")) break;                
            }
            jTextArea1.append("Agent: Shutting down Socket Agent!!\n");
            ControllerSocket.close();
            //close the ServerSocket object            
        } 
        catch (IOException ioe) {
            System.out.println("IOException on socket listen: " + ioe);
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(ChemCamAgentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 153, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
