/*
 * @author truol014
 */
package main;
public class MainFrame extends javax.swing.JFrame {
    private static MainFrame instance = null;    
    private javax.swing.JSplitPane jSplitPane1;
    public static AgentPanel agentPanel1;
    public static ControllerPanel controllerPanel1;
    public MainFrame(){
        initComponents();        
    }
    public static MainFrame getInstance(){
        if(MainFrame.instance == null){
            MainFrame.instance = new MainFrame();
        }
        return MainFrame.instance;
    }
    public static AgentPanel getAgentPanel(){
        return agentPanel1;
    }
    public static ControllerPanel getControllerPanel(){
        return controllerPanel1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents(){
        jSplitPane1 = new javax.swing.JSplitPane();
        controllerPanel1 = new ControllerPanel();
        agentPanel1 = new AgentPanel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setLeftComponent(controllerPanel1);
        jSplitPane1.setRightComponent(agentPanel1);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        pack();
    }
}
